"""empty message

Revision ID: 6984af6b4698
Revises: 
Create Date: 2020-04-19 13:10:30.188641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6984af6b4698'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Comics', sa.Column('series_id', sa.Integer(), nullable=False))
    op.drop_constraint('Comics_series_fkey', 'Comics', type_='foreignkey')
    op.create_foreign_key(None, 'Comics', 'Series', ['series_id'], ['id'])
    op.drop_column('Comics', 'series')
    op.add_column('Series', sa.Column('editorial_id', sa.Integer(), nullable=False))
    op.drop_constraint('Series_editorial_fkey', 'Series', type_='foreignkey')
    op.create_foreign_key(None, 'Series', 'Editorial', ['editorial_id'], ['id'])
    op.drop_column('Series', 'editorial')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Series', sa.Column('editorial', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Series', type_='foreignkey')
    op.create_foreign_key('Series_editorial_fkey', 'Series', 'Editorial', ['editorial'], ['id'])
    op.drop_column('Series', 'editorial_id')
    op.add_column('Comics', sa.Column('series', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Comics', type_='foreignkey')
    op.create_foreign_key('Comics_series_fkey', 'Comics', 'Series', ['series'], ['id'])
    op.drop_column('Comics', 'series_id')
    # ### end Alembic commands ###
