"""empty message

Revision ID: e280eef2a4a1
Revises: 
Create Date: 2020-04-19 12:17:32.462964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e280eef2a4a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Collection')
    op.add_column('Comics', sa.Column('series', sa.Integer(), nullable=False))
    op.drop_constraint('Comics_id_collection_fkey', 'Comics', type_='foreignkey')
    op.create_foreign_key(None, 'Comics', 'Series', ['series'], ['id'])
    op.drop_column('Comics', 'id_collection')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Comics', sa.Column('id_collection', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Comics', type_='foreignkey')
    op.create_foreign_key('Comics_id_collection_fkey', 'Comics', 'Collection', ['id_collection'], ['id'])
    op.drop_column('Comics', 'series')
    op.create_table('Collection',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Collection_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('editorial', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['editorial'], ['Editorial.id'], name='Collection_editorial_fkey'),
    sa.PrimaryKeyConstraint('id', name='Collection_pkey')
    )
    # ### end Alembic commands ###
